replicaCount: 1

image:
  repository: lscr.io/linuxserver/sonarr
  tag: "4.0.12"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8989
  targetPort: 8989
  protocol: TCP

persistence:
  enabled: true
  # storageClassName: ""
  # accessModes:
  #   - ReadWriteMany
  # size: 10Gi
  claimName: your-claim-name

  config: {}
    # subPath: config/sonarr/config
  tv: {}
    # subPath: home/sonarr/tv
  downloads: {}
    # subPath: home/sonarr/downloads

securityContext:
  runAsUser: 1000
  runAsGroup: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
