kube-prometheus-stack:
  prometheus:
    prometheusSpec:
      retention: 100d
      storageSpec:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi
      ## https://github.com/prometheus-operator/kube-prometheus/issues/1392#issuecomment-1411719953
      # ruleSelectorNilUsesHelmValues: false
      # serviceMonitorSelectorNilUsesHelmValues: false
      # podMonitorSelectorNilUsesHelmValues: false
      # probeSelectorNilUsesHelmValues: false

  alertmanager:
    alertmanagerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

  grafana:
    persistence:
      enabled: true
      type: sts
      storageClassName: nfs-client
      accessModes: ["ReadWriteOnce"]
      size: 20Gi
      finalizers:
        - kubernetes.io/pvc-protection

  thanosRuler:
    enabled: true
    thanosRulerSpec:
      storage:
        volumeClaimTemplate:
          spec:
            storageClassName: nfs-client
            accessModes: ["ReadWriteOnce"]
            resources:
              requests:
                storage: 50Gi

