apiVersion: v1
kind: Secret
metadata:
  name: {{ include "reactive-resume.fullname" . | lower }}
type: Opaque
stringData:
  chrome-token: {{ .Values.app.config.chromeToken }}
  database-url: postgresql://{{ .Values.postgresql.global.postgresql.auth.username }}:{{ .Values.postgresql.global.postgresql.auth.password }}@{{ .Release.Name }}-postgresql:{{ .Values.postgresql.global.postgresql.service.ports.postgresql | default 5432 }}/{{ .Values.postgresql.global.postgresql.auth.database }}
  access-token-secret: {{ .Values.app.config.accessTokenSecret }}
  refresh-token-secret: {{ .Values.app.config.refreshTokenSecret }}
  storage-access-key: {{ .Values.minio.auth.rootUser }}
  storage-secret-key: {{ .Values.minio.auth.rootPassword }}
