apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-resume.fullname" . }}-app
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.app.service.type }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "reactive-resume.selectorLabels" . | nindent 4 }}
    component: app

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "reactive-resume.fullname" . }}-chrome
  labels:
    {{- include "reactive-resume.labels" . | nindent 4 }}
spec:
  type: {{ .Values.chrome.service.type }}
  ports:
    - port: {{ .Values.chrome.service.port }}
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    {{- include "reactive-resume.selectorLabels" . | nindent 4 }}
    component: chrome
