apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jellyseerr
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-jellyseerr
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-jellyseerr
    spec:
      containers:
        - name: jellyseerr
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
              name: jellyseerr
              protocol: TCP
          
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: jellyseerr-volume
              subPath: {{ .Values.persistence.subPath }}
          {{- end }}
          
          env:
            {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: jellyseerr-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
