apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-jellyseerr
  labels:
    app: {{ .Release.Name }}-jellyseerr
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Release.Name }}-jellyseerr
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
