apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-{{ .Values.component }}-service
  labels:
    app: {{ .Release.Name }}-{{ .Values.component }}
spec:
  selector:
    app: {{ .Release.Name }}-{{ .Values.component }}
  type: {{ .Values.service.type }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
