{{- if .Values.machineLearning.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-machine-learning
  labels:
    app.kubernetes.io/service: {{ .Release.Name }}-machine-learning
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/name: machine-learning
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
spec:
  type: {{ .Values.machineLearning.service.type }}
  ports:
    - port: {{ .Values.machineLearning.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: machine-learning
{{- end }}
