apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hedgedoc.fullname" . }}
  labels:
    {{- include "hedgedoc.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "hedgedoc.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "hedgedoc.labels" . | nindent 8 }}
    spec:
      containers:
        - name: hedgedoc
          image: "{{ .Values.hedgedoc.image.repository }}:{{ .Values.hedgedoc.image.tag }}"
          imagePullPolicy: {{ .Values.hedgedoc.image.pullPolicy }}
          env:
            - name: CMD_DB_URL
              value: postgres://{{ .Values.postgres.postgresql.credentials.username }}:{{ .Values.postgres.postgresql.credentials.password }}@{{ .Release.Name }}-postgresql-service:5432/{{ .Values.postgres.postgresql.credentials.database }}
            {{- range $key, $value := .Values.hedgedoc.config }}
            - name: {{ $key | quote }}
              value: {{ $value | quote }}
            {{- end }}
          ports:
            - containerPort: 3000
              name: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: uploads
              mountPath: /hedgedoc/public/uploads
      volumes:
        - name: uploads
          persistentVolumeClaim:
            claimName: {{ .Values.hedgedoc.persistence.uploads.claimName | default (include "hedgedoc.fullname" .) }}
          # emptyDir: {}
