apiVersion: v1
kind: Service
metadata:
  name: {{ include "hedgedoc.fullname" . }}
  labels:
    {{- include "hedgedoc.labels" . | nindent 4 }}
spec:
  type: {{ .Values.hedgedoc.service.type }}
  ports:
    - port: {{ .Values.hedgedoc.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "hedgedoc.labels" . | nindent 4 }}
