
{{- if .Values.initdb.scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-scripts
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.initdb.scripts | nindent 2 }}
{{- end }}
