{{- if .Values.initdb.scripts }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-init-scripts
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
data:
  {{- range $filename, $content := .Values.initdb.scripts }}
  {{ $filename }}: |-
{{ $content | indent 4 }}
  {{- end }}
{{- end }}
