apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-postgres-secret
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
type: Opaque
data:
  POSTGRES_USER: {{ .Values.postgresql.credentials.username | b64enc }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.credentials.password | b64enc }}
  POSTGRES_DB: {{ .Values.postgresql.credentials.database | b64enc }}
