apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgresql-service
  labels:
    app: postgresql
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  ports:
    - name: http
      port: {{ .Values.postgresql.service.port }}
      targetPort: {{ .Values.postgresql.service.targetPort }}
  selector:
    app: postgresql
