#####################################################
minio:
  global:
    defaultStorageClass: "nfs-client"
  auth:
    rootUser: "minioadmin"
    rootPassword: "minioadmin"
  defaultBuckets: "appflowy"
#####################################################
redis:
  global:
    defaultStorageClass: "nfs-client"
  auth:
    enabled: false
    sentinel: false
#####################################################
postgresql:
  global:
    defaultStorageClass: "nfs-client"
    security:
      allowInsecureImages: true
    postgresql:
      auth:
        username: "postgres"
        password: "changepassword"
        database: "postgres"
  ## NOTE: This not exist in the original bitnami/postgresql values.yaml
  customUsers:
    usernames: "supabase_auth_admin"
    passwords: "changepassword"
  #############

  image:
    registry: docker.io
    repository: loneexile/pgvector
    tag: "20250101"
    pullPolicy: Always
#####################################################
appflowy_cloud:
  enabled: true
  image:
    repository: appflowyinc/appflowy_cloud
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 9999
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
  config:
    rustLog: "debug" # "trace" "debug" "info" "warn" "error"
    environment: "production"
    s3CreateBucket: "true"
    s3UseMinio: "true"
    s3Region: ""
    s3Bucket: "appflowy"
    mailerSmtpTlsKind: "wrapper" # "none" "wrapper" "required" "opportunistic"
    accessControl: "true"
    databaseMaxConnections: "40"
    aiServerPort: "5001"
  secrets:
    gotrueJwtSecret: "hello456" # Match with gotrue.secrets.jwtSecret
    gotrueJwtExp: "7200" # Match with gotrue.config.jwtExp
    # FIX:
    gotrueExtUrl: "https://appflowy.voidbox.io" # Match with gotrue.config.apiExternalUrl
    gotrueAdminEmail: "admin@example.com" # Match with gotrue.config.adminEmail
    gotrueAdminPassword: "password" # Match with gotrue.secrets.adminPassword
    s3AccessKey: "minioadmin" # Default minio access key
    s3SecretKey: "minioadmin" # Default minio secret key
    mailerSmtpHost: "smtp.gmail.com" # Match with gotrue.secrets.smtpHost
    mailerSmtpPort: "465" # Match with gotrue.secrets.smtpPort
    mailerSmtpUsername: "notify@appflowy.io" # Match with gotrue.secrets.smtpUser
    mailerSmtpEmail: "notify@appflowy.io" # Same as smtp username
    mailerSmtpPassword: "email_sender_password" # Match with gotrue.secrets.smtpPass
    aiOpenaiApiKey: "test" # Match with ai.secrets.openaiApiKey
appflowy_worker:
  enabled: true
  image:
    repository: appflowyinc/appflowy_worker
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  config:
    rustLog: "info"
    environment: "production"
    workerEnvironment: "production"
    workerImportTickInterval: "30"
    s3UseMinio: "true"
    s3Bucket: "appflowy"
    s3Region: ""
  secrets:
    s3AccessKey: "minioadmin"
    s3SecretKey: "minioadmin"
    mailerSmtpHost: "smtp.gmail.com"
    mailerSmtpPort: "465"
    mailerSmtpUsername: "notify@appflowy.io"
    mailerSmtpEmail: "notify@appflowy.io"
    mailerSmtpPassword: "email_sender_password"
  resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

  nodeSelector: {}
  tolerations: []
  affinity: {}
#####################################################
gotrue:
  enabled: true
  image:
    # repository: appflowyinc/gotrue
    # tag: latest
    repository: loneexile/gotrue
    tag: "20241229"
    pullPolicy: Always
  replicaCount: 1
  service:
    type: ClusterIP
    port: 9999
  config:
    adminEmail: "admin@example.com"
    disableSignup: false
    # FIX:
    mailerAutoconfirm: true
    siteUrl: "appflowy-flutter://"
    apiExternalUrl: "https://appflowy.voidbox.io"
    uriAllowList: "*"
    jwtExp: "7200"
    jwtAdminGroupName: "supabase_admin"
    dbDriver: "postgres"
    port: 9999
    mailerUrlPathsConfirmation: "/verify"
    smtpMaxFrequency: "1ns"
    rateLimitEmailSent: "100"
    metricsEnabled: true
    metricsExporter: "prometheus"
  secrets:
    adminPassword: "password"
    jwtSecret: "hello456"
    smtpHost: "smtp.gmail.com"
    smtpPort: "465"
    smtpUser: "email_sender@some_company.com"
    smtpPass: "email_sender_password"
    smtpAdminEmail: "comp_admin@some_company.com"
  oauth:
    google:
      enabled: false
      clientId: ""
      secret: ""
      redirectUri: ""
    apple:
      enabled: false
      clientId: ""
      secret: ""
      redirectUri: ""
    github:
      enabled: false
      clientId: ""
      secret: ""
      redirectUri: ""
    discord:
      enabled: false
      clientId: ""
      secret: ""
      redirectUri: ""
#####################################################
ai:
  enabled: true
  image:
    repository: appflowyinc/appflowy_ai
    tag: latest
    pullPolicy: IfNotPresent
  replicaCount: 1
  service:
    type: ClusterIP
    port: 5001
  config:
    serverPort: 5001
  secrets:
    openaiApiKey: "test"
