apiVersion: v1
kind: Service
metadata:
  name: {{ include "blog.fullname" . }}-service
  labels:
    {{- include "blog.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "blog.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
