apiVersion: v2
name: reactive-resume
description: A Helm chart for Reactive-Resume
version: 0.1.2
appVersion: "4.3.7"
dependencies:
  - name: minio
    version: 14.10.3
    repository: https://charts.bitnami.com/bitnami
  - name: postgresql
    version: 16.3.4
    repository: https://charts.bitnami.com/bitnami
