replicaCount: 1

image:
  repository: frooodle/s-pdf
  tag: "0.36.6"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

environment:
  SECURITY_ENABLE_LOGIN: "true"
  DOCKER_ENABLE_SECURITY: "true"

persistence:
  enabled: true
  claimName: your-claim-name
  mountPath: /configs
  subPath: config/pdf/configs
