apiVersion: v1
kind: Secret
metadata:
  name: tunnel-credentials
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
type: Opaque
data:
  credentials.json: {{ .Values.tunnelCredentials | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-cert
  labels:
    {{- include "cloudflare.labels" . | nindent 4 }}
type: Opaque
data:
  cert.pem: {{ .Values.certPem | quote }}
