apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-drawdb
  labels:
    app: drawdb
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: drawdb
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: drawdb
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: drawdb
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ports.containerPort }}
              hostPort: {{ .Values.ports.hostPort }}

          {{- with .Values.resources }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          {{- end }}
