apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-chrome
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chrome
  template:
    metadata:
      labels:
        app: chrome
    spec:
      containers:
      - name: chrome
        image: {{ .Values.chrome.image.repository }}:{{ .Values.chrome.image.tag }}
        command:
        - chromium-browser
        - --headless
        - --no-sandbox
        - --disable-gpu
        - --disable-dev-shm-usage
        - --remote-debugging-address=0.0.0.0
        - --remote-debugging-port=9222
        - --hide-scrollbars

