apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-env
data:
  HOARDER_VERSION: {{ .Values.env.HOARDER_VERSION }}
  MEILI_MASTER_KEY: {{ .Values.env.MEILI_MASTER_KEY }}
  NEXT_PUBLIC_SECRET: {{ .Values.env.NEXT_PUBLIC_SECRET }}
  NEXTAUTH_SECRET: {{ .Values.env.NEXTAUTH_SECRET }}
  NEXTAUTH_URL: {{ .Values.env.NEXTAUTH_URL }}
  DISABLE_SIGNUPS: {{ .Values.env.DISABLE_SIGNUPS | quote }}
  DISABLE_PASSWORD_AUTH: {{ .Values.env.DISABLE_PASSWORD_AUTH | quote }}
  {{- if .Values.env.OAUTH_WELLKNOWN_URL }}
  OAUTH_WELLKNOWN_URL: {{ .Values.env.OAUTH_WELLKNOWN_URL }}
  {{- end }}
  {{- if .Values.env.OAUTH_CLIENT_SECRET }}
  OAUTH_CLIENT_SECRET: {{ .Values.env.OAUTH_CLIENT_SECRET }}
  {{- end }}
  {{- if .Values.env.OAUTH_CLIENT_ID }}
  OAUTH_CLIENT_ID: {{ .Values.env.OAUTH_CLIENT_ID }}
  {{- end }}
  OAUTH_SCOPE: {{ .Values.env.OAUTH_SCOPE }}
  OAUTH_PROVIDER_NAME: {{ .Values.env.OAUTH_PROVIDER_NAME }}
  OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING: {{ .Values.env.OAUTH_ALLOW_DANGEROUS_EMAIL_ACCOUNT_LINKING | quote }}
  {{- if .Values.env.OPENAI_API_KEY }}
  OPENAI_API_KEY: {{ .Values.env.OPENAI_API_KEY }}
  {{- end }}
  {{- if .Values.env.OPENAI_BASE_URL }}
  OPENAI_BASE_URL: {{ .Values.env.OPENAI_BASE_URL }}
  {{- end }}
  {{- if .Values.env.OLLAMA_BASE_URL }}
  OLLAMA_BASE_URL: {{ .Values.env.OLLAMA_BASE_URL }}
  {{- end }}
  {{- if .Values.env.OLLAMA_KEEP_ALIVE }}
  OLLAMA_KEEP_ALIVE: {{ .Values.env.OLLAMA_KEEP_ALIVE }}
  {{- end }}
  INFERENCE_TEXT_MODEL: {{ .Values.env.INFERENCE_TEXT_MODEL }}
  INFERENCE_IMAGE_MODEL: {{ .Values.env.INFERENCE_IMAGE_MODEL }}
  EMBEDDING_TEXT_MODEL: {{ .Values.env.EMBEDDING_TEXT_MODEL }}
  INFERENCE_CONTEXT_LENGTH: {{ .Values.env.INFERENCE_CONTEXT_LENGTH | quote }}
  INFERENCE_LANG: {{ .Values.env.INFERENCE_LANG }}
  INFERENCE_JOB_TIMEOUT_SEC: {{ .Values.env.INFERENCE_JOB_TIMEOUT_SEC | quote }}
