apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-web
spec:
  ports:
  - port: {{ .Values.web.service.port }}
    protocol: TCP
    targetPort: 3000
  selector:
    app: hoarder-web
  type: {{ .Values.web.service.type }}
