image:
  repository: louislam/uptime-kuma
  tag: "1"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3001

persistence:
  enabled: false
  size: 1Gi
  storageClass: ""
  accessMode: ReadWriteOnce
  subPath: ""
  existingClaim: ""

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}
tolerations: []
affinity: {}
