hedgedoc:
  image:
    repository: quay.io/hedgedoc/hedgedoc
    tag: 1.10.2
    pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    port: 3000

  persistence:
    uploads:
      enabled: true
      size: 10Gi
      storageClass: ""
      accessMode: ReadWriteOnce
      claimName: hedgedoc-uploads
      subPath: config/hedgedoc/uploads

  config:
    CMD_DOMAIN: hedgedoc.domain.com
    CMD_PROTOCOL_USESSL: true
    CMD_URL_ADDPORT: false
    CMD_HSTS_ENABLE: true
    NODE_ENV: production
    CMD_ALLOW_ANONYMOUS: false
    CMD_ALLOW_ANONYMOUS_EDITS: true
    CMD_DEFAULT_PERMISSION: private
    CMD_ALLOW_EMAIL_REGISTER: false
    CMD_ALLOW_GRAVATAR: false

postgres:
  enabled: true
  postgresql:
    image:
      repository: postgres
      tag: 13.4-alpine
      pullPolicy: IfNotPresent
    
    credentials:
      username: "hedgedoc"
      password: "password"
      database: "hedgedoc"

  persistence:
    pgdata: "/var/lib/postgresql/data/"
    claimName: hedgedoc-postgres
    mountPaths:
      - path: /var/lib/postgresql/data
        subPath: config/hedgedoc/db/data

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
