apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
data:
  POSTGRESQL_USERNAME: {{ .Values.postgresql.credentials.username }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.credentials.database }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.credentials.password }}
