apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
data:
  POSTGRESQL_USERNAME: {{ .Values.postgresql.auth.username }}
  POSTGRESQL_DATABASE: {{ .Values.postgresql.auth.database }}
  POSTGRESQL_PASSWORD: {{ .Values.postgresql.auth.password }}
