apiVersion: v1
kind: ConfigMap
metadata:
  name: sonar-config
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
data:
  SONARQUBE_DATABASE_USER: {{ .Values.postgresql.credentials.username | quote }}
  SONARQUBE_DATABASE_PASSWORD: {{ .Values.postgresql.credentials.password | quote }}
  SONARQUBE_DATABASE_HOST: "postgres"
  SONARQUBE_DATABASE_NAME: {{ .Values.postgresql.credentials.database | quote }}
  JAVA_OPTS: {{ .Values.sonarqube.javaOpts | quote }}
