apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-sonar-config
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
data:
  SONARQUBE_DATABASE_USER: {{ .Values.postgresql.auth.username | quote }}
  SONARQUBE_DATABASE_PASSWORD: {{ .Values.postgresql.auth.password | quote }}
  SONARQUBE_DATABASE_HOST: {{ .Release.Name }}-postgres
  SONARQUBE_DATABASE_NAME: {{ .Values.postgresql.auth.database | quote }}
  JAVA_OPTS: {{ .Values.sonarqube.javaOpts | quote }}
