apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "postgresql.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "postgresql.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.postgresql.security.fsGroup }}
      containers:
      - name: postgres
        image: "{{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}"
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.postgresql.service.port }}
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        envFrom:
        - configMapRef:
            name: postgres
        volumeMounts:
        - name: postgres
          mountPath: /bitnami/postgresql
          subPath: config/postgresql
      volumes:
      - name: postgres
        persistentVolumeClaim:
          claimName: {{ .Values.global.persistentVolumeClaim }}
