apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "sonarqube.labels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "sonarqube.labels" . | nindent 8 }}
    spec:
      securityContext:
        fsGroup: {{ .Values.postgresql.securityContext.fsGroup }}
      containers:
      - name: postgres
        image: {{ .Values.postgresql.image.repository }}:{{ .Values.postgresql.image.tag }}
        imagePullPolicy: {{ .Values.postgresql.image.pullPolicy }}
        ports:
        - containerPort: 5432
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: {{ .Values.postgresql.auth.allowEmptyPassword | quote }}
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-postgres
        volumeMounts:
        - name: postgres-data
          mountPath: /bitnami/postgresql
          subPath: config/postgresql
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: {{ .Values.global.persistence.existingClaim }}
