apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-postgres
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  ports:
  - port: 5432
    name: postgres
  selector:
    {{- include "sonarqube.labels" . | nindent 4 }}
