apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    {{- include "postgresql.labels" . | nindent 4 }}
spec:
  ports:
  - port: {{ .Values.postgresql.service.port }}
    name: postgres
  selector:
    {{- include "postgresql.labels" . | nindent 4 }}
