apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calcom.fullname" . }}-env
type: Opaque
stringData:
  NEXT_PUBLIC_WEBAPP_URL: {{ .Values.calcom.env.NEXT_PUBLIC_WEBAPP_URL | quote }}
  NEXT_PUBLIC_API_V2_URL: {{ .Values.calcom.env.NEXT_PUBLIC_API_V2_URL | quote }}
  NEXT_PUBLIC_LICENSE_CONSENT: {{ .Values.calcom.env.NEXT_PUBLIC_LICENSE_CONSENT | quote }}
  CALCOM_TELEMETRY_DISABLED: {{ .Values.calcom.env.CALCOM_TELEMETRY_DISABLED | quote }}
  NEXTAUTH_SECRET: {{ .Values.calcom.env.NEXTAUTH_SECRET | quote }}
  CALENDSO_ENCRYPTION_KEY: {{ .Values.calcom.env.CALENDSO_ENCRYPTION_KEY | quote }}
