replicaCount: 1

image:
  repository: loneexile/drawdb
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ports:
   containerPort: 80
   hostPort: 3000

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 200m
  #   memory: 256Mi

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: drawdb.local
      paths:
        - path: /
          pathType: Prefix
