global:
  storageClass: ""
  persistentVolumeClaim: "jenkins-pvc"

postgresql:
  service:
    port: 5432
  image:
    repository: bitnami/postgresql
    tag: "17.2.0"
    pullPolicy: IfNotPresent
  labels:
    app: postgres
  security:
    fsGroup: 2000
  credentials:
    username: sonar_user
    database: sonar_db
    password: S0N4RQUB3

sonarqube:
  image:
    repository: bitnami/sonarqube
    tag: 10.7.0
    pullPolicy: IfNotPresent
  labels:
    app: sonar
  resources:
    requests:
      memory: 1Gi
    limits:
      memory: 4Gi
  javaOpts: "-Duser.timezone=Asia/Jakarta -Xmx2048m"
