replicaCount: 1

image:
  repository: ghcr.io/danvergara/morphos-server
  tag: "0.6.0"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

persistence:
  enabled: true
  existingClaim: your-claim-name

resources: {}
  # limits:
  #   cpu: 500m
  #   memory: 512Mi
  # requests:
  #   cpu: 250m
  #   memory: 256Mi

containerPort: 8080
volumeMountPath: /tmp
volumeSubPath: config/morphos/tmp
