replicaCount: 1
component: memos
image:
  repository: ghcr.io/usememos/memos
  pullPolicy: Always
  tag: 0.23.0-pre
  digest: ""
storage:
  useEmptyDir: true
  sizeLimit: 500Mi
  mountPath: /var/opt/memos
  subPath: config/memos
  claimName: memos-pvc
service:
  type: ClusterIP
  protocol: TCP
  port: 5230
  targetPort: 5230
