apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-frontend
  labels:
    app: perplexica-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: perplexica-frontend
  template:
    metadata:
      labels:
        app: perplexica-frontend
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}
        imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
        env:
        - name: NEXT_PUBLIC_API_URL
          value: {{ .Values.frontend.env.NEXT_PUBLIC_API_URL }}
        - name: NEXT_PUBLIC_WS_URL
          value: {{ .Values.frontend.env.NEXT_PUBLIC_WS_URL }}
        ports:
        - containerPort: 3000
