apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-searxng
  labels:
    app: searxng
spec:
  selector:
    app: searxng
  ports:
    - protocol: TCP
      port: {{ .Values.searxng.service.port }}
      targetPort: 8080
