apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-livebook
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: livebook
  template:
    metadata:
      labels:
        app: livebook
    spec:
      containers:
        - name: livebook
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 8080
              name: livebook-1
              protocol: TCP
            - containerPort: 8081
              name: livebook-2
              protocol: TCP
          
          {{- if .Values.persistence.enabled }}
          volumeMounts:
            - mountPath: {{ .Values.persistence.mountPath }}
              name: livebook-volume
              subPath: {{ .Values.persistence.subPath }}
          {{- end }}
          
          env:
          {{- range $key, $value := .Values.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
          {{- end }}
          
          {{- if .Values.resources }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          {{- end }}
      
      {{- if .Values.persistence.enabled }}
      volumes:
        - name: livebook-volume
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.existingClaim }}
      {{- end }}
