apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-livebook-service
  labels:
    app: livebook
spec:
  selector:
    app: livebook
  ports:
  {{- range .Values.service.ports }}
    - protocol: {{ .protocol }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      name: {{ .name }}
  {{- end }}
