apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "morphos.fullname" . }}
  labels:
    {{- include "morphos.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "morphos.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "morphos.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.containerPort }}
          volumeMounts:
            - name: morphos-storage
              mountPath: {{ .Values.volumeMountPath }}
              subPath: {{ .Values.volumeSubPath }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
      volumes:
        - name: morphos-storage
          persistentVolumeClaim:
            {{- if .Values.persistence.enabled }}
            claimName: {{ .Values.persistence.existingClaim }}
            {{- end }}
