apiVersion: v1
kind: Service
metadata:
  name: {{ include "morphos.fullname" . }}
  labels:
    {{- include "morphos.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "morphos.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
