apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "common.labels" . | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := .Values.secrets }}
  {{ $key }}: {{ $value }}
  {{- end }}
