apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nocodb.fullname" . }}
  labels:
    {{- include "nocodb.labels" . | nindent 4 }}
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "nocodb.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "nocodb.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: NC_DB
              value: "pg://{{ .Release.Name }}-postgresql:5432?u={{ .Values.postgres.postgresql.credentials.username }}&p={{ .Values.postgres.postgresql.credentials.password }}&d={{ .Values.postgres.postgresql.credentials.database }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /usr/app/data
              {{- if .Values.persistence.subPath }}
              subPath: {{ .Values.persistence.subPath }}
              {{- end }}
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.persistence.claimName | default (include "nocodb.fullname" .) }}
