name: Release Charts

on:
  push:
    branches:
      - main

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install yq
        run: |
          wget https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64 -O /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Add maintainers to Chart.yaml
        run: |
          set -e
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Processing $chart/Chart.yaml"
              yq eval '.maintainers' .cr.yaml > maintainers.tmp
              if [ -s maintainers.tmp ]; then
                yq eval-all 'select(fileIndex == 0) *+ {"maintainers": (select(fileIndex == 1) | .)}' \
                  "$chart/Chart.yaml" maintainers.tmp > "$chart/Chart.yaml.new"
                mv "$chart/Chart.yaml.new" "$chart/Chart.yaml"
                echo "Successfully updated maintainers in $chart/Chart.yaml"
              else
                echo "Warning: No maintainers found in .cr.yaml"
              fi
              rm maintainers.tmp
            fi
          done

      - name: Install Helm
        uses: azure/setup-helm@v4.2.0

      - name: Add Helm repositories
        run: |
          helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo add le https://loneexile.github.io/chart

      - name: Build Helm dependencies
        env:
          HELM_EXPERIMENTAL_OCI: "1"
        run: |
          for chart in charts/*; do
            if [ -f "$chart/Chart.yaml" ]; then
              echo "Building dependencies for $chart"
              helm dependency build "$chart"
            fi
          done

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.5.0
        with:
          config: .cr.yaml
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
