{{- if .Values.ai.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ai
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai
spec:
  replicas: {{ .Values.ai.replicaCount }}
  selector:
    matchLabels:
      app: ai
  template:
    metadata:
      labels:
        app: ai
    spec:
#TODO: temp this
      initContainers:
        - name: check-db-ready
          image: "{{ index .Values "postgresql-ha" "postgresql" "image" "repository" }}:{{ index .Values "postgresql-ha" "postgresql" "image" "tag" }}"
          command:
            - /bin/bash
            - -c
            - |
              until PGPASSWORD=$POSTGRES_PASSWORD psql -h $POSTGRES_HOST -U $POSTGRES_USER -d $POSTGRES_DB -c '\q'; do
                echo "Waiting for postgres..."
                sleep 60
              done
              echo "PostgreSQL is ready"
          env:
            - name: POSTGRES_HOST
              value: {{ .Release.Name }}-postgresql-ha-pgpool
            - name: POSTGRES_USER
              value: {{ index .Values "postgresql-ha" "pgpool" "customUsers" "usernames" }}
            - name: POSTGRES_PASSWORD
              value: "{{ index .Values "postgresql-ha" "pgpool" "customUsers" "passwords" }}"
            - name: POSTGRES_DB
              value: {{ index .Values "postgresql-ha" "global" "postgresql" "database" }}
      containers:
        - name: ai
          image: "{{ .Values.ai.image.repository }}:{{ .Values.ai.image.tag }}"
          imagePullPolicy: {{ .Values.ai.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ai.config.serverPort }}
              protocol: TCP
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-ai-secrets
          env:
            - name: APPFLOWY_AI_SERVER_PORT
              value: {{ .Values.ai.config.serverPort | quote }}
          resources:
            {{- toYaml .Values.ai.resources | nindent 12 }}
          {{- if .Values.ai.livenessProbe }}
          livenessProbe:
            {{- toYaml .Values.ai.livenessProbe | nindent 12 }}
          {{- end }}
          {{- if .Values.ai.readinessProbe }}
          readinessProbe:
            {{- toYaml .Values.ai.readinessProbe | nindent 12 }}
          {{- end }}
{{- end }}
