{{- if .Values.ai.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-ai
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
    app.kubernetes.io/component: ai
spec:
  type: {{ .Values.ai.service.type }}
  ports:
    - port: {{ .Values.ai.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: ai
{{- end }}
