apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gotrue-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  GOTRUE_ADMIN_PASSWORD: {{ .Values.gotrue.secrets.adminPassword | b64enc }}
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.secrets.jwtSecret | b64enc }}
  DATABASE_URL: {{ .Values.gotrue.secrets.databaseUrl | b64enc }}
  GOTRUE_SMTP_HOST: {{ .Values.gotrue.secrets.smtpHost | b64enc }}
  GOTRUE_SMTP_PORT: {{ .Values.gotrue.secrets.smtpPort | b64enc }}
  GOTRUE_SMTP_USER: {{ .Values.gotrue.secrets.smtpUser | b64enc }}
  GOTRUE_SMTP_PASS: {{ .Values.gotrue.secrets.smtpPass | b64enc }}
  GOTRUE_SMTP_ADMIN_EMAIL: {{ .Values.gotrue.secrets.smtpAdminEmail | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ai-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.ai.secrets.openaiApiKey | b64enc }}
  APPFLOWY_AI_DATABASE_URL: {{ .Values.ai.secrets.databaseUrl | b64enc }}
  APPFLOWY_AI_REDIS_URL: {{ .Values.ai.secrets.redisUrl | b64enc }}
