apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-gotrue-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  GOTRUE_ADMIN_PASSWORD: {{ .Values.gotrue.secrets.adminPassword | b64enc }}
  GOTRUE_JWT_SECRET: {{ .Values.gotrue.secrets.jwtSecret | b64enc }}
  DATABASE_URL: {{ printf "postgresql://%s:%s@%s-postgresql-ha-pgpool:5432/%s"
    (index .Values "postgresql-ha" "pgpool" "customUsers" "usernames")
    (index .Values "postgresql-ha" "pgpool" "customUsers" "passwords")
    .Release.Name
    (index .Values "postgresql-ha" "global" "postgresql" "database")
  | b64enc }}
  GOTRUE_SMTP_HOST: {{ .Values.gotrue.secrets.smtpHost | b64enc }}
  GOTRUE_SMTP_PORT: {{ .Values.gotrue.secrets.smtpPort | b64enc }}
  GOTRUE_SMTP_USER: {{ .Values.gotrue.secrets.smtpUser | b64enc }}
  GOTRUE_SMTP_PASS: {{ .Values.gotrue.secrets.smtpPass | b64enc }}
  GOTRUE_SMTP_ADMIN_EMAIL: {{ .Values.gotrue.secrets.smtpAdminEmail | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-ai-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  OPENAI_API_KEY: {{ .Values.ai.secrets.openaiApiKey | b64enc }}
  APPFLOWY_AI_DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s-postgresql-ha-pgpool:5432/%s"
    (index .Values "postgresql-ha" "global" "postgresql" "username")
    (index .Values "postgresql-ha" "global" "postgresql" "password")
    .Release.Name
    (index .Values "postgresql-ha" "global" "postgresql" "database")
  | b64enc }}
  APPFLOWY_AI_REDIS_URL: {{ .Values.ai.secrets.redisUrl | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-appflowy-cloud-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  APPFLOWY_DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s-postgresql-ha-pgpool:5432/%s?sslmode=disable"
    (index .Values "postgresql-ha" "global" "postgresql" "username")
    (index .Values "postgresql-ha" "global" "postgresql" "password")
    .Release.Name
    (index .Values "postgresql-ha" "global" "postgresql" "database")
  | b64enc }}
  APPFLOWY_REDIS_URI: {{ printf "redis://%s-redis-master:6379" .Release.Name | b64enc }}
  APPFLOWY_GOTRUE_JWT_SECRET: {{ .Values.appflowy_cloud.secrets.gotrueJwtSecret | b64enc }}
  APPFLOWY_GOTRUE_JWT_EXP: {{ .Values.appflowy_cloud.secrets.gotrueJwtExp | b64enc }}
  APPFLOWY_GOTRUE_BASE_URL: {{ printf "http://%s-gotrue:9999" .Release.Name | b64enc }}
  APPFLOWY_GOTRUE_EXT_URL: {{ .Values.appflowy_cloud.secrets.gotrueExtUrl | b64enc }}
  APPFLOWY_GOTRUE_ADMIN_EMAIL: {{ .Values.appflowy_cloud.secrets.gotrueAdminEmail | b64enc }}
  APPFLOWY_GOTRUE_ADMIN_PASSWORD: {{ .Values.appflowy_cloud.secrets.gotrueAdminPassword | b64enc }}
  APPFLOWY_S3_MINIO_URL: {{ printf "http://%s-minio:9000" .Release.Name | b64enc }}

  APPFLOWY_S3_ACCESS_KEY: {{ .Values.appflowy_cloud.secrets.s3AccessKey | b64enc }}
  APPFLOWY_S3_SECRET_KEY: {{ .Values.appflowy_cloud.secrets.s3SecretKey | b64enc }}
  APPFLOWY_MAILER_SMTP_HOST: {{ .Values.appflowy_cloud.secrets.mailerSmtpHost | b64enc }}
  APPFLOWY_MAILER_SMTP_PORT: {{ .Values.appflowy_cloud.secrets.mailerSmtpPort | b64enc }}
  APPFLOWY_MAILER_SMTP_USERNAME: {{ .Values.appflowy_cloud.secrets.mailerSmtpUsername | b64enc }}
  APPFLOWY_MAILER_SMTP_EMAIL: {{ .Values.appflowy_cloud.secrets.mailerSmtpEmail | b64enc }}
  APPFLOWY_MAILER_SMTP_PASSWORD: {{ .Values.appflowy_cloud.secrets.mailerSmtpPassword | b64enc }}
  APPFLOWY_AI_SERVER_HOST: {{ .Values.appflowy_cloud.secrets.aiServerHost | b64enc }}
  APPFLOWY_AI_OPENAI_API_KEY: {{ .Values.appflowy_cloud.secrets.aiOpenaiApiKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-appflowy-worker-secrets
  labels:
    {{- include "gotrue.labels" . | nindent 4 }}
type: Opaque
data:
  APPFLOWY_WORKER_REDIS_URL: {{ printf "redis://%s-redis-master:6379" .Release.Name | b64enc }}
  APPFLOWY_WORKER_DATABASE_URL: {{ printf "postgresql+psycopg://%s:%s@%s-postgresql-ha-pgpool:5432/%s"
    (index .Values "postgresql-ha" "global" "postgresql" "username")
    (index .Values "postgresql-ha" "global" "postgresql" "password")
    .Release.Name
    (index .Values "postgresql-ha" "global" "postgresql" "database")
  | b64enc }}
  APPFLOWY_S3_MINIO_URL: {{ printf "http://%s-minio:9000" .Release.Name | b64enc }}
  APPFLOWY_S3_ACCESS_KEY: {{ .Values.appflowy_worker.secrets.s3AccessKey | b64enc }}
  APPFLOWY_S3_SECRET_KEY: {{ .Values.appflowy_worker.secrets.s3SecretKey | b64enc }}
  APPFLOWY_MAILER_SMTP_HOST: {{ .Values.appflowy_worker.secrets.mailerSmtpHost | b64enc }}
  APPFLOWY_MAILER_SMTP_PORT: {{ .Values.appflowy_worker.secrets.mailerSmtpPort | b64enc }}
  APPFLOWY_MAILER_SMTP_USERNAME: {{ .Values.appflowy_worker.secrets.mailerSmtpUsername | b64enc }}
  APPFLOWY_MAILER_SMTP_EMAIL: {{ .Values.appflowy_worker.secrets.mailerSmtpEmail | b64enc }}
  APPFLOWY_MAILER_SMTP_PASSWORD: {{ .Values.appflowy_worker.secrets.mailerSmtpPassword | b64enc }}
