apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "jenkins.fullname" . }}-pvc
  namespace: {{ .Release.Namespace }}
spec:
  storageClassName: {{ .Values.persistence.storageClass }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
