apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: token-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/service-account.name: jenkins-admin
