apiVersion: v1
kind: Service
metadata:
  name: {{ include "jenkins.fullname" . }}-service
  namespace: {{ .Release.Namespace }}
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/path: /
    prometheus.io/port: '8080'
spec:
  selector:
    {{- include "jenkins.labels" . | nindent 4 }}
  ports:
    - name: httpport
      port: {{ .Values.jenkins.service.port }}
      targetPort: 8080
    - name: jnlpport
      port: {{ .Values.jenkins.service.jnlpPort }}
      targetPort: 50000
